# **Nivell 1 - EDA estructurat i neteja bàsica**

Tenim un dataset d'empleats obtingut a partir d'una enquesta interna. Abans de poder extreure conclusions, cal assegurar-nos que les dades són correctes, consistents i analitzables.

**Exercici 1: Exploració inicial del dataset**

**Objectiu**: entendre l’estructura general del dataset i detectar possibles problemes abans de començar a netejar o transformar dades.
En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:

>* » Quantes files i columnes té el dataset?
>* » Quin tipus de dades conté cada columna?
>* » Hi ha files duplicades?
>* » Les dades semblen coherents a primera vista?
>* » Detectes possibles problemes o inconsistències evidents?

Per fer-ho, hauràs de:

## Exercici 1: Exploració inicial del dataset

In [100]:
import pandas as pd

### Importación del fichero

In [101]:
df = pd.read_excel('sprint8_complex.xlsx',header = 3)

### » Dimensiones del dataset

In [102]:
df.shape

(1007, 20)

### » Muestra representativa de filas

In [103]:
df.head()

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [104]:
df.sample(5)

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
586,586,Irene,DÃ­az Ramos,28269700D,Espanya,Barcelona,32.0,13.0,3000.0,F,"1,064 â‚¬",NaN,NaN,Grup A,Analista,0.0,False,NaN,NaN,17.5
588,588,Katharina,SchrÃ¶der Wolf,91877605Z,Alemanya,MÃ¼nchen,24.0,9.0,1965.0,F,958 â‚¬,True,NaN,Grup A,Data Analyst,3.0,False,NaN,NaN,8.7
814,814,Sara,Ramos,83864238C,Espanya,Madrid,26.0,7.0,1975.0,Home,"2,491 â‚¬",NaN,NaN,Grup C,Data Analyst,0.0,True,-50.0,NaN,42.0
748,748,Pau,Ramos,53941883H,Espanya,Girona,0.0,99.0,2026.0,D,"1,825 â‚¬",NaN,True,Grup B,TÃ¨cnic IT,NaN,NaN,NaN,NaN,15.6
207,207,VÃ­ctor,Ferrer Casals,94644676Q,Espanya,ValÃ¨ncia,5.0,8.0,1984.0,H,854 â‚¬,NaN,True,Grup A,Administratiu,NaN,True,80000.0,0.5,13.9

### » Revisar tipos de variables

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1007 non-null   int64
 1   Nom                         1006 non-null   object
 2   Cognoms                     1006 non-null   object
 3   DNI                         1006 non-null   object
 4   País d'origen               1006 non-null   object
 5   Ciutat                      1006 non-null   object
 6   Dia de Naixement            1006 non-null   float64
 7   Mes de Naixement            1006 non-null   float64
 8   Any de Naixement            1006 non-null   float64
 9   Gènere                      966 non-null    object
 10  Salari mensual              1006 non-null   object
 11  Fills                       419 non-null    object
 12  No Fills                    585 non-null    object
 13  Grup Professional           1005 non-null   object
 14  CÃ rrec                     1005 non-null   object
 15  Nombre_fills                709 non-null    float64
 16  Te_cotxe                    658 non-null    object
 17  Km_anuals                   315 non-null    float64
 18  Consum_mitja_L_100km        261 non-null    float64
 19  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(7), int64(1), object(12)
memory usage: 157.5+ KB

In [106]:
df.dtypes

Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

### » Detectar filas duplicadas

In [107]:
df.duplicated().sum()

np.int64(0)

**RESULTADO ANALISIS:** Los datos no parecen coherentes, ya que presentan problemas de validez, consistencia y calidad. La cabecera se encuentra en la fila 4, hay carácteres corruptos, problemas de codificación, columnas etiquetadas como Unnamed, edades que no corresponden con el año indicado, valores numéricos poco plausibles, salarios con formatos diferentes, valores NaN en columnas relevantes para el análisis y la columna que debe asignarse como DATE está en formato float.

## **Exercici 2: Validacions bàsiques de les dades i decisions d'eliminació**

**Objectiu**: assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?

» Què faràs amb les files duplicades o registres repetits?

» Hi ha valors obligatoris que falten o informació incoherent?

» Detectes formats incorrectes, errors de codificació o valors impossibles?

**Important:**

En aquest exercici no s'espera que imputis dades, sinó que decideixis quins registres poden formar part de l'anàlisi i quins no, argumentant sempre el criteri utilitzat.

> Si el text "s'entén però està mal escrit" → codificació

> Si el text "està ben escrit però no és útil per a l'anàlisi" → validació

Concretament, hauràs de:

### » Corregir possibles problemes de codificació i accentuació en els noms de les columnes i en els valors de text, si escau.

Función **corregir_codificacion** comprueba si el valor es una cadena. Si lo es, intenta recodificarla desde latin1 a utf‑8 para corregir caracteres extraños. Si la conversión falla, devuelve el texto original. Si el valor no es una cadena, lo retorna sin modificar.

In [108]:
def corregir_codificacion(valor):
  if isinstance(valor, str):
    try:
      return valor.encode('latin1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
      return valor
  return valor

 Aplicamos la función **corregir_codificacion** a cada nombre de columna del DataFrame. Recorre todas las columnas y devuelve una lista con los nombres ya corregidos, sustituyendo caracteres mal codificados.

In [109]:
df.columns = [corregir_codificacion(columna)
  for columna in df.columns]

Identificamos todas las columnas de tipo texto del DataFrame y aplicamos la función **corregir_codificacion** a cada una. Así corrige caracteres mal codificados dentro de las celdas, limpiando valores corruptos y dejando todas las columnas de texto con codificación coherente.

In [110]:
columnas_text = df.select_dtypes(include="object").columns

for columna in columnas_text:
  df[columna] = df[columna].apply(corregir_codificacion)

In [111]:
df.head()

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

Este código corrige manualmente un caso que la función automática no pudo arreglar. Busca filas donde el nombre aparece como “Ã‰lise” y lo sustituye por “Élise”, eliminando los caracteres mal codificados que aún quedan tras la limpieza general.

In [112]:
df.loc[df["Nom"] == "Ã‰lise", "Nom"] = "Élise"

##### Columna 'Nom', registro ???

In [113]:
df[df['Nom'].astype(str).str.contains(r"[^a-zA-Z0-9À-ÿ\s]", regex=True, na=False)]

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [114]:
df = df[df['Nom'] != "???"]

#### Eliminar columna Unnamed 0 ya que no contiene información relebante para el analisis de empleados. Si queremos un id de empleados ya tenemos los DNIs.

In [115]:
df = df.drop(columns=['Unnamed: 0'])

### » Detectar i eliminar files duplicades exactes, indicant quants registres s'han eliminat.

In [116]:
df.duplicated().sum()

np.int64(4)

In [117]:
df[df.duplicated()]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
40,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

Selecciona todas las filas que aparecen duplicadas en el DataFrame y devuelvo únicamente esos duplicados exactos en un nuevo DataFrame.

In [118]:
df_duplicats_exactes = df[df.duplicated(keep=False)]

In [119]:
df_duplicats_exactes

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
36,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
40,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
372,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
730,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

In [120]:
df_duplicats_exactes = df_duplicats_exactes.sort_values(by ='DNI')

Elimino 4 filas duplicadas quedandome solo con la fila original de cada duplicado.

In [121]:
df = df.drop_duplicates(keep='first')

### » Comprovar la unicitat del DNI. En cas de detectar DNIs duplicats, hauràs d'analitzar la coherència de la informació associada i descartar o anul·lar els registres que no siguin fiables, justificant clarament la decisió presa.

In [122]:
df['DNI'].duplicated().sum()

np.int64(11)

In [123]:
dnis_duplicados = df[df['DNI'].duplicated(keep = False)]

In [124]:
dnis_duplicados= (dnis_duplicados.sort_values('DNI'))

In [125]:
df = df[~df['DNI'].duplicated(keep = False)]

He creado una variable para guardar los DNIs duplicados por si más adelante fueran necesarios. Tras revisar estos DNIs, no encuentro coherencia suficiente como para mantener sus registros dentro del DataFrame, por lo que resulta adecuado excluirlos del análisis principal.

### » Identificar els camps clau que no haurien de contenir valors nuls, detectar registres amb informació insuficient i eliminar únicament aquelles files completament buides o amb informació irrecuperable o no substituïble, explicant per què no és possible ni raonable imputar-les.

Identificación y eliminación de filas con todos los valores NaN

In [126]:
df[df.isna().all(axis=1)]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
df = df.dropna(how='all')

Identificación de valores NaN en campos clave

In [128]:
columnes_clau = [
    'Nom',
    'Cognoms',
    'DNI',
    'País d\'origen',
    'Ciutat',
    'Dia de Naixement',
    'Mes de Naixement',
    'Any de Naixement',
    'Fills',
    'Nombre_fills',
    'Gènere',
    'Salari mensual',
    'Grup Professional']

In [129]:
files_nan = df[df[columnes_clau].isna().any(axis=1)]

In [130]:
files_nan.shape

(602, 19)

In [131]:
df['Gènere'].isna().sum()

np.int64(39)

In [132]:
df['Nombre_fills'].isna().sum()

np.int64(294)

In [133]:
df['Fills'].isna().sum()

np.int64(574)

**RESULTADO ANALISIS:** He identificado 39 filas con valores *NaN* en campos importantes. En todas, el único dato crítico ausente es **Género**, mientras que el resto de información relevante está completa. Por ello, no se eliminan: siguen aportando valor analítico y permiten mantener un conjunto de datos más completo y útil.

## **Exercici 3: Transformacions necessàries i preparació del dataset**
Objectiu: preparar el dataset perquè sigui coherent, analitzable i estructuralment correcte abans de realitzar qualsevol anàlisi descriptiva. En aquest exercici hauràs d'aplicar transformacions bàsiques però essencials, orientades a millorar la qualitat de les dades i facilitar l'anàlisi posterior.

Aspectes a revisar i transformar:

» Els valors categòrics estan normalitzats i són consistents?

» Els valors nuls són coherents amb la informació disponible?

» Hi ha redundància de variables que pugui generar problemes analítics?

» Les variables contextuals (com temperatura, salari) estan completes i preparades per a l'anàlisi?

Important

en aquest exercici no es tracta d'eliminar registres, sinó de transformar, normalitzar i preparar les dades perquè siguin analitzables de manera rigorosa en els nivells següents.

Concretament, hauràs de:

###  » Normalitzar els valors categòrics per evitar ambigüitats (per exemple, valors que representen el mateix concepte però estan escrits de manera diferent).

#### columna Gènere

In [134]:
df['Gènere'].value_counts(dropna = False)

Gènere
D       317
H       274
Dona    117
F       107
Home     50
NaN      39
M        34
A        24
NC       23
Name: count, dtype: int64

In [135]:
dicc_genere = {
    "H": "Home",
    "M": "Home",
    "D": "Dona",
    "F": "Dona"}

In [136]:
df["Gènere"] = df["Gènere"].replace(dicc_genere)

In [137]:
df['Gènere'].value_counts(dropna = False)

Gènere
Dona    541
Home    358
NaN      39
A        24
NC       23
Name: count, dtype: int64

In [138]:
dicc_nom = {
    "Irene": "Dona",
    "Hugo" : "Home",
    "Marta": "Dona",
    "Xavier": "Home",
    "Katharina": "Dona",
    "Lucas": "Home",
    "Alejandro": "Home",
    "Laura": "Dona",
    "Marco": "Home",
    "Chiara": "Dona",
    "Huho": "Home",
    "Alba": "Dona",
    "Mia": "Dona",
    "Felix": "Home",
    "Joana": "Dona",
    "Luca": "Home",
    "Gabrielle": "Home",
    "Simone" : "Home",
    "Camille": "Dona",
    "Elena" : "Dona",
    "Sara": "Dona",
    "Víctor": "Home",
    "Thomas": "Home",
    "Marina": "Dona",
    "David": "Home",
    "Laia": "Dona",
    "Núria": "Dona",
    "Anna": "Dona",
    "Pol": "Home",
    "Marta": "Dona",
    "Alexia": "Dona",
    "Carmen": "Dona",
    "Antoine": "Home",
    "Lucía": "Dona",
    "Alessandro": "Home",
    'Noa' : 'Dona',
    'Sergio': 'Home',
    'Pau' : 'Home',
    'Marie' : 'Dona',
    'Claudia': 'Dona',
    'Riccardo': 'Home',
    'Elias': 'Dona',
    'Aina': 'Dona',
    'Nil' : 'Home',
    'Carlos': 'Home',
    'Marc': 'Home',
    'Adrià': 'Home',
    'Lucía': 'Home'}

In [139]:
mask = df["Gènere"].isin(["A", "NC"]) | df["Gènere"].isna()

Aplicamos el dicc_nom solo a las filas con valores A, NC y NaN.

In [140]:
df.loc[mask, "Gènere"] = df.loc[mask, "Nom"].map(dicc_nom)

In [141]:
df['Gènere'].value_counts(dropna=False)

Gènere
Dona    582
Home    401
NaN       2
Name: count, dtype: int64

In [142]:
df[df['Gènere'].isna()]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
410,Gabriele,Lombardi,14930347Y,Itàlia,Firenze,8.0,1.0,2000.0,NaN,1432â‚¬,True,NaN,Grup B,Data Analyst,3.0,NaN,NaN,NaN,10.5
895,Ilaria,Rizzo,42823207X,Itàlia,Torino,16.0,9.0,1998.0,NaN,"2,180 â‚¬",NaN,True,Grup C,Administratiu,NaN,NaN,NaN,NaN,15.0

Gènere: se han detectado varias formas de representar el género (H,M,D,F) que he normalizado como 'Home' y 'Dona'. También he revisado los registros con valores NaN, A y NC. Cuando el nombre permitía clasificarlos he asignado un valor correspondiente. En los casos que el nombre no era posible clasificarlos claramente he asignado el valor NaN. Finalmente la variable queda normalizada en Home, Dona y 8 valores nulos.

#### columna Càrrec

In [143]:
df['Càrrec'].value_counts(dropna = False)

Càrrec
Data Analyst             139
Tècnic IT                128
Senior analyst           122
Responsable de vendes    121
Analista                 112
Analista junior          106
Administratiu            102
Cap de projecte           93
Project lead              17
Data analyst              17
Cap de Projecte           13
Analyst                    9
Admin.                     6
Name: count, dtype: int64

In [144]:
dicc_carrecs = {
    'Data analyst': 'Data analyst',
    'Cap de Projecte': 'Cap de projecte',
    'Project lead': 'Cap de projecte',
    'Cap de projectes' : 'Cap de projecte',
    'Analyst': 'Data analyst',
    'Admin.': 'Administratiu',
    'Analista': 'Data analyst',
    'Senior analyst': 'Analista senior',
    'Tècnic IT': 'Tècnic IT',
    'Data Analyst': 'Data analyst',
    'Responsable de vendes': 'Responsable de vendes',
    'Analista junior': 'Analista junior',
    'Administratiu' : 'Administratiu',
    'Cap de projecte' : 'Cap de projecte'}

In [145]:
df['Càrrec'] = df['Càrrec'].replace(dicc_carrecs)

In [146]:
df['Càrrec'].value_counts(dropna = False)

Càrrec
Data analyst             277
Tècnic IT                128
Cap de projecte          123
Analista senior          122
Responsable de vendes    121
Administratiu            108
Analista junior          106
Name: count, dtype: int64

Càrrec: He detectado diferentes maneras de representar algunos cargos principalmente por diferencias entre mayúsculas y minúsculas, abreviaciones y idiomas. He unificado las categorias.

#### columna Grup Profesional

In [147]:
pd.crosstab(df['Càrrec'], df['Grup Professional'])

Grup Professional      Grup A  Grup B  Grup C  Grup D
Càrrec
Administratiu              47      38      19       4
Analista junior            59      34      11       2
Analista senior            57      44      15       6
Cap de projecte            51      49      19       4
Data analyst              120     103      44      10
Responsable de vendes      59      40      16       6
Tècnic IT                  63      42      15       8

No podemos establecer una equivalencia directa entre Càrrec y Grup Professional. No utilizaremos Càrrec para rellenar o corregir Grup Professional.

###  » Revisar la coherència dels valors nuls, assegurant que:

#### Les persones que tenen quilometratge anual i consum mitjà associats disposen de cotxe. En els casos en què consti consum mitjà però no quilometratge anual, caldrà decidir com resoldre aquesta incoherència de manera justificada.

#### columnes : Te cotxe, consum mitja l 100km, Km anuals

In [148]:
df['Te_cotxe'].value_counts(dropna = False)

Te_cotxe
NaN      342
True     323
False    320
Name: count, dtype: int64

Compruebo que todas las filas donde Te cotxe es NaN, las columnas Km_anuals y Consum_mitja_L_100km es valor 0

In [149]:
df.loc[df['Te_cotxe'].isna(), ['Km_anuals', 'Consum_mitja_L_100km']].sum()

Km_anuals               0.0
Consum_mitja_L_100km    0.0
dtype: float64

Buscamos entre las personas que tienen coche si tienen valores NaN en las columnas Km_anuals y Consum_mitja_l_100km.

In [150]:
df.loc[df['Te_cotxe'] == True, ['Km_anuals', 'Consum_mitja_L_100km']].isna().sum()

Km_anuals               17
Consum_mitja_L_100km    66
dtype: int64

Buscamos registros con Km_anuals y Consum_mitja_L_100km pero la persona no tiene coche.

In [151]:
df.loc[df["Te_cotxe"] == False,["Km_anuals", "Consum_mitja_L_100km"]].notna().sum()

Km_anuals               4
Consum_mitja_L_100km    0
dtype: int64

In [152]:
df.loc[(df["Te_cotxe"] == False) & (df["Km_anuals"].notna())]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
270,Oriol,Torres Vila,10443906N,Espanya,Tarragona,8.0,9.0,1962.0,Dona,1632â‚¬,True,NaN,Grup B,Responsable de vendes,1.0,False,0.0,NaN,15.1
698,Aina,Díaz,83677009H,Espanya,Barcelona,26.0,2.0,1992.0,Dona,"2,242 â‚¬",True,NaN,Grup B,Cap de projecte,1.0,False,0.0,NaN,18.7
743,Sergio,Pérez,35553337Y,Espanya,Valladolid,4.0,7.0,1980.0,Home,"2,574 â‚¬",NaN,True,Grup C,Responsable de vendes,0.0,False,0.0,NaN,10.8
922,Simone,Esposito,88357247Z,Itàlia,Torino,15.0,2.0,1967.0,Home,926 â‚¬,NaN,True,Grup A,Analista junior,NaN,False,0.0,NaN,NaN

Convertimos los registros con valor 0.0 de Km_anuals a Nan.

In [153]:
mask_Nan_Km_anual = (df['Te_cotxe'] == False) & (df['Km_anuals'] == 0)

In [154]:
df.loc[mask_Nan_Km_anual, 'Km_anuals'] = pd.NA

In [155]:
df.loc[(df["Te_cotxe"] == False) &(df["Km_anuals"].notna()),["Nom", "Te_cotxe", "Km_anuals", "Consum_mitja_L_100km"]]

Empty DataFrame
Columns: [Nom, Te_cotxe, Km_anuals, Consum_mitja_L_100km]
Index: []

Se revisaron las variables Te_cotxe, Km_anuals y Consum_mitja_L_100km. Los registros con Te_cotxe desconocido tampoco presentan datos de kilometraje ni consumo, por lo que no es posible determinar si disponen de vehículo. Se identificaron casos con coche y consumo informado pero sin kilometraje anual, que se mantiene como nulo. Además, se detectaron cuatro casos con Te_cotxe = False y Km_anuals = 0 (valores sustituido por NaN).

### » Unificar la informació sobre fills en una única columna, ja que mantenir diverses columnes amb informació complementària no és òptim i pot generar problemes analítics (redundància o multicolinealitat). Les persones que tenen un valor en el nombre de fills efectivament tenen fills.

In [156]:
df["Fills"].value_counts(dropna=False)

Fills
NaN     574
True    411
Name: count, dtype: int64

In [157]:
df["No Fills"].value_counts(dropna=False)

No Fills
True    572
NaN     413
Name: count, dtype: int64

Proceso revisión

In [158]:
df.loc[(df['Fills'] == True) & (df['No Fills'] == True),
       ['Fills', 'No Fills', 'Nombre_fills']]

    Fills No Fills  Nombre_fills
11   True     True           1.0
17   True     True           0.0
155  True     True           0.0
165  True     True           1.0
168  True     True           0.0
205  True     True           1.0
219  True     True           0.0
221  True     True           1.0
239  True     True           4.0
257  True     True           0.0
280  True     True           0.0
283  True     True           0.0
289  True     True           0.0
293  True     True           0.0
320  True     True           0.0
326  True     True           0.0
330  True     True           1.0
354  True     True           0.0
440  True     True           0.0
441  True     True           3.0
453  True     True           0.0
496  True     True           0.0
531  True     True           3.0
571  True     True           0.0
578  True     True           3.0
595  True     True           0.0
601  True     True           0.0
627  True     True           0.0
667  True     True           0.0
678  True     True           0.0
740  True     True           0.0
742  True     True           0.0
767  True     True           0.0
795  True     True           0.0
800  True     True           0.0
803  True     True           0.0
841  True     True           0.0
854  True     True           0.0
866  True     True           2.0
889  True     True           0.0
898  True     True           0.0
947  True     True           1.0
976  True     True           NaN
983  True     True           NaN
987  True     True           0.0
991  True     True           NaN

In [159]:
df.loc[(df['Fills'] == False) & (df['No Fills'] == False),
       ['Fills', 'No Fills', 'Nombre_fills']]

Empty DataFrame
Columns: [Fills, No Fills, Nombre_fills]
Index: []

Creo la columna Te_Fills teniendo como referencia la columna Nombre_fills

In [160]:
df.loc[df["Nombre_fills"] > 0, "Te_Fills"] = True
df.loc[df["Nombre_fills"] == 0, "Te_Fills"] = False

In [161]:
df['Te_Fills'].value_counts(dropna = False)

Te_Fills
True     390
False    301
NaN      294
Name: count, dtype: int64

Elimino las columnas Fills y No Fills

In [162]:
df = df.drop(columns=["Fills", "No Fills"])

### » Validar la temperatura mitjana. En cas que aquesta informació falti, hauràs d'imputar-la utilitzant un criteri raonable (per ciutat o per un nivell superior justificat).

#### columna : Temperatura mitjana ciutat

In [163]:
df['Temperatura_mitjana_ciutat'].value_counts(dropna = False)

Temperatura_mitjana_ciutat
 NaN     66
-5.0     21
 38.0    18
 15.0    16
 15.4    14
         ..
 6.7      1
 8.2      1
 20.7     1
 23.5     1
 24.3     1
Name: count, Length: 187, dtype: int64

In [164]:
df.groupby('País d\'origen')['Ciutat'].nunique()

País d'origen
Alemanya     8
Espanya     15
França       8
Itàlia       8
Noruega      5
Name: Ciutat, dtype: int64

In [165]:
medias_temperaturas = df.groupby('País d\'origen')['Temperatura_mitjana_ciutat'].mean()

Tomamos como referencia las medias de temperatura de cada país para imputarlas a los valores NaN de la columna Temperatura_mitjana_ciutat.

In [166]:
mask_nan_temp = df['Temperatura_mitjana_ciutat'].isna()

In [167]:
df.loc[mask_nan_temp, 'Temperatura_mitjana_ciutat'] = (
    df.loc[mask_nan_temp, 'País d\'origen'].map(medias_temperaturas))

In [168]:
df['Temperatura_mitjana_ciutat'].value_counts(dropna = False)

Temperatura_mitjana_ciutat
 16.506955    53
-5.000000     21
 38.000000    18
 15.000000    16
 15.600000    14
              ..
 6.700000      1
 8.200000      1
 20.700000     1
 23.500000     1
 24.300000     1
Name: count, Length: 191, dtype: int64

Temperatura_mitjana_ciutat: He detectado 66 valores NaN. Como todas las ciudades tenian valores de temperatura he calculado la temperatura media de cada ciudad y he imputado estos valores a los valores NaN. Los valores que ya existían NO se modifican.

### » Revisar i imputar els salaris faltants, aplicant criteris analítics coherents (com ara càrrec, grup professional, ciutat, gènere o franja d'edat).

In [169]:
df['Salari mensual'].value_counts(dropna = False)

Salari mensual
n/d               14
mil vuit-cents     9
dos mil            7
tres mil           6
1,644 â‚¬          4
                  ..
1479â‚¬            1
1,840 â‚¬          1
1,338 â‚¬          1
2,855 â‚¬          1
2,349 â‚¬          1
Name: count, Length: 841, dtype: int64

In [170]:
dicc = {
    'mil vuit-cents': 1800,
    'dos mil': 2000,
    'tres mil': 3000}

In [171]:
df['Salari mensual'] = df['Salari mensual'].replace(dicc)

In [172]:
df['Salari mensual'].value_counts(dropna = False)

Salari mensual
n/d          14
1800          9
2000          7
3000          6
1,644 â‚¬     4
             ..
1479â‚¬       1
1,840 â‚¬     1
1,338 â‚¬     1
2,855 â‚¬     1
2,349 â‚¬     1
Name: count, Length: 841, dtype: int64

In [173]:
df['Salari mensual'] = (
    df['Salari mensual']
    .astype(str)
    .str.replace('[^0-9]', '', regex=True)
    .str.strip())

In [174]:
df['Salari mensual'] = pd.to_numeric(df['Salari mensual'], errors='coerce')

In [175]:
df['Salari mensual'].isna().sum()

np.int64(14)

In [176]:
df[df['Salari mensual'].isna()]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Te_Fills
93,Pau,Gil,48532662J,Espanya,Girona,0.0,13.0,2026.0,Dona,NaN,Grup A,Data analyst,4.0,False,NaN,NaN,14.500000,True
146,Luca,Gallo Ferrari,74468586Y,Itàlia,Torino,20.0,11.0,2000.0,Dona,NaN,Grup A,Analista junior,NaN,False,NaN,NaN,14.400000,NaN
159,Anna,Fernández,65446317R,Espanya,Palma,10.0,9.0,1982.0,Dona,NaN,Grup A,Cap de projecte,2.0,False,NaN,NaN,16.506955,True
254,Zoé,Thomas Dubois,89260394J,França,Marseille,13.0,8.0,1992.0,Home,NaN,Grup A,Analista senior,2.0,NaN,NaN,NaN,20.600000,True
291,Thomas,Lefebvre Moreau,85300576W,França,Lille,28.0,8.0,1977.0,Home,NaN,Grup C,Analista senior,4.0,False,NaN,NaN,12.900000,True
307,David,Moreno Soler,66528833P,Espanya,Barcelona,29.0,9.0,1994.0,Home,NaN,Grup C,Data analyst,NaN,False,NaN,NaN,18.500000,NaN
384,Pau,Ribera Díaz,81965066H,Espanya,Barcelona,23.0,2.0,1989.0,Dona,NaN,Grup B,Data analyst,0.0,NaN,NaN,NaN,13.400000,False
446,Anna,Domènech,68131630Y,Espanya,Las Palmas de Gran Canaria,13.0,2.0,2004.0,Dona,NaN,Grup A,Tècnic IT,4.0,False,NaN,NaN,16.506955,True
860,Thomas,David,27341287F,França,Bordeaux,8.0,6.0,1972.0,Dona,NaN,Grup A,Tècnic IT,1.0,False,NaN,NaN,16.200000,True
875,Laia,Vidal Romero,39330100H,Espanya,Sevilla,24.0,8.0,2004.0,Dona,NaN,Grup A,Cap de projecte,2.0,False,NaN,NaN,20.300000,True
917,Claudia,Gil Fernández,19213734E,Espanya,Palma,3.0,7.0,1971.0,Home,NaN,Grup C,Analista senior,NaN,True,81219.0,6.6,13.300000,NaN
953,Luca,Rizzo Ferrari,28245984Z,Itàlia,Torino,29.0,6.0,2002.0,Home,NaN,Grup A,Analista senior,2.0,False,NaN,NaN,13.600000,True
955,Jordi,Martínez Gil,13976162W,Espanya,Zaragoza,3.0,8.0,1967.0,Dona,NaN,Grup A,Cap de projecte,1.0,NaN,NaN,NaN,-5.000000,True
956,Alexia,Moreno Domènech,61249115R,Espanya,Zaragoza,10.0,5.0,2004.0,Dona,NaN,Grup A,Cap de projecte,NaN,True,9017.0,0.5,13.000000,NaN

Compruebo si hay alguna relación para imputar algun Salari mensual con valores NaN.

In [177]:
df[df['Càrrec'] == 'Data analyst']

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Te_Fills
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,Home,1478.0,Grup B,Data analyst,2.0,False,NaN,NaN,18.300000,True
19,Adrià,Ribera,63640499F,Espanya,Palma,16.0,7.0,2002.0,Dona,889.0,Grup A,Data analyst,NaN,NaN,NaN,NaN,19.200000,NaN
36,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,Dona,1614.0,Grup B,Data analyst,3.0,NaN,NaN,NaN,10.600000,True
47,Aina,Fernández,38468360C,Espanya,Zaragoza,-5.0,0.0,3000.0,Home,1939.0,Grup C,Data analyst,1.0,True,78064.0,NaN,16.506955,True
51,Francesca,Ferrari,60015814G,Itàlia,Venezia,24.0,12.0,1964.0,Home,1773.0,Grup B,Data analyst,3.0,False,NaN,NaN,11.500000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Laura,Bauer Zimmermann,34637932B,Alemanya,Köln,6.0,3.0,1993.0,Home,1644.0,Grup B,Data analyst,NaN,False,NaN,NaN,11.500000,NaN
996,Lucía,Roca Vila,21702378D,Espanya,Alacant,32.0,0.0,1940.0,Home,1158.0,Grup A,Data analyst,NaN,NaN,NaN,NaN,19.400000,NaN
997,Jordi,Hernández,67755039Y,Espanya,Zaragoza,12.0,10.0,1961.0,Dona,1074.0,Grup A,Data analyst,1.0,True,80000.0,12.0,12.000000,True
998,Chloé,Dubois,66354268T,França,Nice,2.0,12.0,1958.0,Home,1954.0,Grup B,Data analyst,1.0,NaN,NaN,NaN,11.700000,True
999,Adrià,Vila Díaz,57511543T,Espanya,Palma,31.0,12.0,1991.0,Home,2010.0,Grup C,Data analyst,1.0,False,NaN,NaN,-10.000000,True

Guardo en una variable los registros NaN de Salari mensual. Pero los mantengo en el Dataset original.

In [178]:
salari_mensual_nans = df[df['Salari mensual'].isna()]

In [179]:
df['Salari mensual'].isna().sum()

np.int64(14)

In [180]:
df['Salari mensual']

0       1469.0
1       2718.0
2       1358.0
3       1478.0
4       1284.0
         ...
996     1158.0
997     1074.0
998     1954.0
999     2010.0
1001    2290.0
Name: Salari mensual, Length: 985, dtype: float64

In [181]:
df = df.rename(columns={'Salari mensual': 'Salari mensual (€)'})

In [182]:
df.columns

Index(['Nom', 'Cognoms', 'DNI', 'País d'origen', 'Ciutat', 'Dia de Naixement',
       'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual (€)',
       'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals',
       'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat', 'Te_Fills'],
      dtype='object')

### » Columnas: Any, Mes i Dia de Naixement

Unificaré las 3 columnas en una sola. Nos permitirá conocer la edat y agilizar algunas consultas así como facilitar y organizar el DataFrame

In [183]:
print(df['Dia de Naixement'].isna().sum())
print(df['Mes de Naixement'].isna().sum())
print(df['Any de Naixement'].isna().sum())

0
0
0

In [184]:
df['Dia de Naixement'] = pd.to_numeric(df['Dia de Naixement'], errors='coerce')
df['Mes de Naixement'] = pd.to_numeric(df['Mes de Naixement'], errors='coerce')
df['Any de Naixement'] = pd.to_numeric(df['Any de Naixement'], errors='coerce')

In [185]:
df['Data_naixement'] = pd.to_datetime(
    {'year': df['Any de Naixement'],
     'month': df['Mes de Naixement'],
     'day': df['Dia de Naixement']},
     errors='coerce')

In [186]:
df['Data_naixement'].isna().sum()

np.int64(77)

In [187]:
df[df['Data_naixement'].isna()]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual (€),Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,Te_Fills,Data_naixement
9,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,Home,1450.0,Grup A,Analista senior,4.0,False,NaN,NaN,20.100000,True,NaT
39,Guillem,Vila,92874006W,Espanya,Murcia,0.0,99.0,3000.0,Home,2000.0,Grup A,Analista senior,0.0,NaN,NaN,NaN,16.506955,False,NaT
41,Paul,Richard Laurent,43567615Z,França,Bordeaux,32.0,99.0,2019.0,Dona,1967.0,Grup B,Cap de projecte,NaN,False,NaN,NaN,15.200000,NaN,NaT
47,Aina,Fernández,38468360C,Espanya,Zaragoza,-5.0,0.0,3000.0,Home,1939.0,Grup C,Data analyst,1.0,True,78064.0,NaN,16.506955,True,NaT
53,Aina,Serra,29226889H,Espanya,València,0.0,0.0,2019.0,Dona,1866.0,Grup B,Tècnic IT,NaN,False,NaN,NaN,21.100000,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,Alejandro,Soler López,41786590C,Espanya,Zaragoza,32.0,99.0,2026.0,Home,1095.0,Grup A,Data analyst,0.0,NaN,NaN,NaN,19.800000,False,NaT
926,David,Pérez,52298598B,Espanya,Murcia,-5.0,0.0,2019.0,Dona,779.0,Grup A,Analista junior,0.0,NaN,NaN,NaN,19.000000,False,NaT
958,Ida,Johansen Kristiansen,41407343V,Noruega,Bergen,32.0,99.0,2019.0,Dona,2759.0,Grup C,Analista senior,NaN,False,NaN,NaN,9.100000,NaN,NaT
981,Giulia,Romano,34747698K,Itàlia,Torino,32.0,0.0,2026.0,Dona,1316.0,Grup B,Tècnic IT,NaN,True,20000.0,9.1,38.000000,NaN,NaT
996,Lucía,Roca Vila,21702378D,Espanya,Alacant,32.0,0.0,1940.0,Home,1158.0,Grup A,Data analyst,NaN,NaN,NaN,NaN,19.400000,NaN,NaT

Después de unificar las 3 columnas en una sola 'Data_naixement' quedan valores NaT (Not a time). La comprobación me lleva a dejarlos como valores nulos ya que la información de la que disponemos corresponde a valores imposibles.

Borramos columnas Dia naixement, Mes naixement, Any naixement.

In [188]:
df = df.drop(columns=['Dia de Naixement', 'Mes de Naixement', 'Any de Naixement'])

## **Exercici 4: Primeres anàlisis descriptives**

**Objectiu:** obtenir una primera visió global del dataset un cop s'han aplicat les transformacions bàsiques, mitjançant estadístiques descriptives i comparacions simples entre grups rellevants.

Aspectes a revisar i analitzar:

>* » Construir taules resum descriptives.
>* » Fer comparacions bàsiques entre grups rellevants.

Concretament, hauràs de:

>* » Construir taules resum descriptives de salaris com una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere. Ordena la taula en funció del sou mig.
>* » Crear una taula resum amb el salari mig per gènere (files) i país d'origen (columnes). Afegeix-hi les mitjanes als marges de la taula. Aplica format condicional a la taula per veure en un color més intens els valors més elevats.

**(EXTRA)**

Abans d'interpretar mitjanes, medianes o totals, cal preguntar-se si aquests valors permeten una comparació justa entre grups. Quan les mides dels grups són diferents, els percentatges o ràtios solen oferir una visió més objectiva que els valors absoluts.

Podries repetir l’anàlisi utilitzant percentatges i ràtios salarials, i comparar com canvia la interpretació respecte als valors absoluts?

 **Important**

No es tracta d'extreure conclusions complexes, sinó de descriure què mostren les dades

### Tabla resumen por Salaris mensual y Gènere

In [189]:
taula_sou_genere = (
    df.groupby('Gènere')['Salari mensual (€)']
    .agg(['mean', 'median', 'min', 'max'])
    .sort_values(by='mean', ascending=False)).round(2)

In [190]:
taula_sou_genere

           mean  median    min     max
Gènere
Home    1674.37  1478.5  673.0  3672.0
Dona    1490.53  1349.0  701.0  3564.0

### Tabla resumen con Salario medio por Gènere (filas) y País de origen (columnas)

In [191]:
taula_pivot = pd.pivot_table(
    df,
    values='Salari mensual (€)',
    index='Gènere',
    columns='País d\'origen',
    aggfunc='mean',
    margins=True,
    margins_name='Mitjana total'
).round(2)

In [192]:
taula_pivot

País d'origen  Alemanya  Espanya   França   Itàlia  Noruega  Mitjana total
Gènere
Dona            1431.97  1490.31  1395.24  1492.44  1758.04        1490.53
Home            2061.62  1672.80  1653.44  1666.00  1479.00        1674.37
Mitjana total   1602.50  1566.63  1501.01  1562.53  1641.23        1565.66

### Aplicar formato condicional (color más intenso para valores más altos)

In [193]:
taula_pivot.style.format('{:.2f}').background_gradient(cmap='Blues')

### EXTRA — Porcentatjes y rátios salariales

####   Porcentaje del salario respecto al máximo del género

In [194]:
ratio_sou = (df.groupby('Gènere')['Salari mensual (€)']
      .apply(lambda x: x / x.max()).round(2))

In [195]:
ratio_sou.head()

Gènere
Dona    0    0.41
        2    0.38
        4    0.36
        5    0.58
        6    0.66
Name: Salari mensual (€), dtype: float64

####  Percentaje del salario medio respecto al total

In [196]:
percent_sou_genere = (df.groupby('Gènere')['Salari mensual (€)'].mean()/ df['Salari mensual (€)'].mean()* 100).round(2)

In [197]:
percent_sou_genere

Gènere
Dona     95.17
Home    106.91
Name: Salari mensual (€), dtype: float64

**CONCLUSIÓN:** La comparación percentual muestra que el sueldo medio de los hombres es superior al sueldo medio global del dataset (108.70%), meintras que el de las mujeres es inferior (95.13%).
Esto indica en términos relativos, que los hombres tienen un salario medio del 8,7% superior a la media. Mientras, que las mujeres se situa un 4,8% por debajo. Esta representación porcentual permite comparar los grupos de manera más justa, indepenientemente de la media de cada grupo.

# **Nivell 2 - Anàlisi amb dades enriquides i estructures múltiples**

Per a aquest nivell, es facilita informació externa que simula dades reals utilitzades per una empresa en processos d'anàlisi i presa de decisions salarials.

Fitxer JSON de política salarial: L'empresa disposa d'un fitxer JSON que defineix les regles d'increment salarial anual. Aquest document estableix increments base per grup professional i ajustos addicionals segons factors personals (edat, fills) i contextuals. Aquest tipus d'estructura és habitual en sistemes interns de recursos humans, ja que permet modificar les polítiques sense alterar el codi.

 Fitxer CSV de ciutats europees: Es proporciona també un fitxer CSV amb informació contextual sobre diverses ciutats europees (país, índex de cost de vida, qualitat del transport públic i tipus de clima). Aquest dataset representa una font externa de dades utilitzada per enriquir l'anàlisi salarial en funció de l'entorn geogràfic on resideix cada persona.

## Exercici 1: Enriquiment mitjançant datasets externs

Objectiu: ampliar el dataset principal integrant informació contextual externa i avaluar l'impacte analític de les decisions de fusió.
Aspectes a revisar i analitzar

>* » Les diferents fonts de dades són coherents i compatibles entre si per poder calcular un salari ajustat?
>* » La informació contextual incorporada (cost de vida, polítiques salarials) és suficient per aplicar increments de manera consistent?
>* » Hi ha buits d'informació que impedeixin calcular correctament l'increment salarial en alguns registres?
>* » És necessari prendre decisions analítiques quan la informació contextual és parcial o absent?
>* » Com poden aquestes decisions influir en el càlcul del salari ajustat i en la seva interpretació posterior?

Concretament, hauràs de:

### » Integrar el dataset principal amb:
El dataset contextual de ciutats.
La política salarial definida en format JSON

In [257]:
ciutats = pd.read_csv("ciutats_context.csv", encoding="latin1")

In [258]:
ciutats.columns

Index(['Ciutat', 'País', 'Cost_vida_index', 'Transport_public_score',
       'Clima_tipus'],
      dtype='object')

In [259]:
dicc_ciutats = {
    'Munchen': 'München',
    'A Coru\\u00f1a' : 'A Coruña'}

In [260]:
ciutats['Ciutat'] = ciutats['Ciutat'].replace(dicc_ciutats)

Ciudades que estan en 'df' y en 'ciutats'

In [261]:
df.loc[df['Ciutat'].isin(ciutats['Ciutat']), 'Ciutat'].value_counts(dropna = False)

Ciutat
Palma                         57
Barcelona                     54
Murcia                        52
Sevilla                       48
Zaragoza                      47
Bilbao                        46
A Coruña                      45
Las Palmas de Gran Canaria    45
Tarragona                     44
Valladolid                    44
Alacant                       43
Girona                        43
Madrid                        40
València                      39
Napoli                        18
Firenze                       18
Torino                        16
Roma                          15
Oslo                          14
Marseille                     13
Milano                        13
Genova                        12
Bordeaux                      11
Bergen                        10
Lille                         10
Hamburg                        9
Paris                          8
Frankfurt                      7
Stuttgart                      7
Lyon                           6
Berlin                         6
Venezia                        5
München                        5
Leipzig                        5
Name: count, dtype: int64

Ciudades que estan en 'df' pero no aparecen en 'ciutats'

In [262]:
df.loc[~df['Ciutat'].isin(ciutats['Ciutat']), 'Ciutat'].value_counts(dropna=False)

Ciutat
Màlaga        53
Toulouse      15
Nantes        12
Bologna       11
Nice          11
Stavanger      9
Trondheim      6
Düsseldorf     5
Tromsø         4
Köln           4
Name: count, dtype: int64

Creo una variable con las ciudades no coincidentes

In [204]:
df_no_match = df.loc[~df['Ciutat'].isin(ciutats['Ciutat']), ['País d\'origen', 'Ciutat']]

Agrupo las df['Ciutat'] faltantes en 'ciutats' por paises

In [263]:
df_no_match.groupby('País d\'origen')['Ciutat'].unique()

País d'origen
Alemanya                [Düsseldorf, Köln]
Espanya                           [Màlaga]
França            [Toulouse, Nice, Nantes]
Itàlia                           [Bologna]
Noruega     [Stavanger, Trondheim, Tromsø]
Name: Ciutat, dtype: object

Aplico merge entre ambas tablas df y ciutats. Resultado df_merge

In [264]:
df_merge = pd.merge(df, ciutats, how='left', on='Ciutat')

Identificar filas donde 'Cost_vida_index' no coincide

In [265]:
mask_no_city = df_merge['Cost_vida_index'].isna()

Columnas que queremos para calcular  las medias de los valores 'Cost_vida_index' y 'Transport_public_score'

In [266]:
cols_ciutats = ['Cost_vida_index', 'Transport_public_score']

Calculamos la media por país de las columnas 'Cost_vida_index' y 'Transport_public_score' del dataset df_merge para poder imputar estos valores en las ciudades no coincidentes.

In [209]:
mitjanes_pais = df_merge.groupby('País')[cols_ciutats].mean()

Imputar la media de los paises a las ciudades que no coinciden

In [267]:
df_merge.loc[mask_no_city, cols_ciutats] = (
    mitjanes_pais.reindex(df_merge.loc[mask_no_city, 'País d\'origen']).values)

Mantener valores 'Clima' como NaN

In [211]:
df_merge.loc[mask_no_city, 'Clima_tipus'] = pd.NA

Importamos json

In [212]:
import json
with open('politica_salarial.json') as f:
    politica = json.load(f)

### » Calcular un increment salarial total combinant:
Grup professional.
Situació familiar.
Franja d'edat.
Cost de vida de la ciutat.

### » Identificar quins registres no poden rebre algun dels ajustos i explicar-ne el motiu.

### » Decidir, de manera raonada, com tractar aquests casos en el càlcul del salari ajustat, justificant l'impacte analític de la decisió presa.

In [268]:
for grup, incremento in politica["base_increment_by_group"].items():
    print(grup, incremento)

Grup A 5.0
Grup B 3.5
Grup C 2.0
Grup D 8.0

Creamos una nueva columna llamada Increment_base_grup en el DataFrame df_merge.
Esta columna contiene el valor del incremento base asociado a cada registro según su Grup Professional.
Para ello, utilizamos la función .map(), que relaciona cada grupo profesional del DataFrame con el valor correspondiente definido en la clave base_increment_by_group del archivo JSON politica.

In [294]:
df_merge["Increment_base_grup"] = df_merge["Grup Professional"].map(
    politica["base_increment_by_group"])

Creamos un diccionario llamado map_fills que relaciona los valores booleanos de la columna Te Fills del DataFrame (True/False) con los valores correspondientes definidos en la clave children_adjustment del archivo JSON politica.
Este diccionario actúa como puente entre ambos formatos y permite asignar automáticamente el incremento salarial por situación familiar a cada registro mediante la función .map().

In [293]:
map_fills = {
    True: politica['children_adjustment']['has_children'],
    False: politica['children_adjustment']['no_children']}

Aplicamos el diccionario map_fills sobre la columna Te_Fills del DataFrame df_merge.
Este diccionario relaciona los valores booleanos (True/False) con los porcentajes definidos en la política salarial del archivo JSON.
De esta forma, cada registro recibe automáticamente el incremento correspondiente según si la persona tiene hijos o no, generando la nueva columna Increment_fills.

In [292]:
df_merge['Increment_fills'] = df_merge['Te_Fills'].map(map_fills)

Importamos la librería datetime para obtener la fecha actual y calcular la edad de cada persona en función de su columna Data_naixement.
Restamos la fecha de nacimiento a la fecha de hoy, convertimos la diferencia en días a años y almacenamos el resultado en la nueva columna Edat del DataFrame df_merge.

In [271]:
from datetime import datetime
avui = datetime.today()

In [272]:
df_merge['Edat'] = (avui - df_merge['Data_naixement']).dt.days // 365

Creamos una función llamada classificar_edat que clasifica cada edad en un rango.
La función comprueba primero si el valor es nulo y, en caso contrario, asigna la franja correspondiente según los intervalos establecidos (18–29, 30–44, 45–59 y 60+).
Esta clasificación nos permite vincular posteriormente cada franja con el ajuste salarial definido en el archivo JSON politica.

In [273]:
def classificar_edat(edat):
    if pd.isna(edat):
        return None
    if 18 <= edat <= 29:
        return "18-29"
    elif 30 <= edat <= 44:
        return "30-44"
    elif 45 <= edat <= 59:
        return "45-59"
    else:
        return "60+"

Creamos la columna Franja_edat aplicando la función classificar_edat sobre la columna Edat.
Esta función asigna a cada registro el rango de edad correspondiente (18–29, 30–44, 45–59 o 60+), lo que nos permite vincular posteriormente cada franja con el ajuste salarial definido en el archivo JSON politica.

In [274]:
df_merge['Franja_edat'] = df_merge['Edat'].apply(classificar_edat)

Creamos la columna Increment_edat aplicando la función .map() sobre la columna Franja_edat.
Esta operación vincula cada rango de edad con el porcentaje de ajuste definido en la clave age_adjustment del archivo JSON politica.
De este modo, cada registro recibe automáticamente el incremento salarial correspondiente según su franja de edad.

In [275]:
df_merge['Increment_edat'] = df_merge['Franja_edat'].map(politica['age_adjustment'])

 Creamos la función cost_band para categorizar el Cost_vida_index

In [276]:
def cost_band(x):
    if pd.isna(x): return None
    if x < 65: return "low"
    if 65 <= x < 80: return "medium"
    if x >= 80: return "high"

Creamos la columna Cost_band aplicando la función cost_band sobre la columna Cost_vida_index, lo que nos permite clasificar cada ciudad en los niveles “low”, “medium” o “high”.
A continuación, extraemos del archivo JSON la clave cost_of_living_adjustment y aplicamos un mapeo sobre Cost_band para generar la columna Increment_cost, que contiene el porcentaje de ajuste salarial correspondiente a cada nivel de coste de vida.

In [278]:
df_merge["Cost_band"] = df_merge["Cost_vida_index"].apply(cost_band)

In [279]:
cost_adj = politica["cost_of_living_adjustment"]
df_merge["Increment_cost"] = df_merge["Cost_band"].map(cost_adj)

Creamos el inc_transport. Categorizamos el Transport_public_score

In [280]:
def transport_band(x):
    if pd.isna(x): return None
    if x < 7: return "low"
    if 7 <= x < 8.5: return "medium"
    if x >= 8.5: return "high"

In [281]:
df_merge["Transport_band"] = df_merge["Transport_public_score"].apply(transport_band)

transport_adj = politica["transport_adjustment"]
df_merge["Increment_transport"] = df_merge["Transport_band"].map(transport_adj)

In [289]:
transport_adj = politica["transport_adjustment"]

Creamos la columna Increment_transport aplicando la función .map() sobre la columna Transport_band.
Este mapeo relaciona cada categoría de transporte público (low, medium, high) con el porcentaje de ajuste definido en la clave transport_adjustment del archivo JSON politica.
De esta forma, cada registro recibe automáticamente el incremento salarial correspondiente según el nivel de transporte de su ciudad.

In [290]:
df_merge["Increment_transport"] = df_merge["Transport_band"].map(transport_adj)

In [295]:
df_merge["Increment_total_percent"] = (
    df_merge["Increment_base_grup"]
    + df_merge["Increment_fills"]
    + df_merge["Increment_edat"]
    + df_merge["Increment_cost"]
    + df_merge["Increment_transport"])

In [296]:
max_inc = politica["rules"]["max_total_increment_percent"]
df_merge["inc_total_percent_capped"] = df_merge["Increment_total_percent"].clip(upper=max_inc)

In [231]:
(df_merge["Increment_total_percent"] > 15).any()

np.False_

## Exercici 2: Reestructuració del dataset

Objectiu: preparar el dataset per a anàlisis comparatives i/o visuals. Convertir informació dispersa en format llarg:
Salaris
Mobilitat
Context climàtic etc

Aspectes a revisar i analitzar

>* » Existeixen variables que representen conceptes similars o relacionats, però estan distribuïdes en diferents columnes?

>* »El format actual del dataset facilita o dificulta:
>>* comparacions entre magnituds.
>>* agregacions per grups.

>* »Quin impacte té la forma del dataset (ample vs llarg) en la lectura i interpretació de les dades?

Concretament, hauràs de:

### » Reestructurar el dataset utilitzant melt() per convertir-lo a format llarg, definint prèviament:
les columnes que actuen com a identificadores (per exemple: persona, ciutat, grup professional, gènere, etc.).
les columnes que passen a representar valors mesurats (per exemple: salaris, mobilitat, variables contextuals).

### » Analitzar per què el format llarg és més adequat per:
realitzar comparacions entre diferents tipus de variables.
calcular estadístics agregats.

In [232]:
df_merge.columns

Index(['Nom', 'Cognoms', 'DNI', 'País d'origen', 'Ciutat', 'Gènere',
       'Salari mensual (€)', 'Grup Professional', 'Càrrec', 'Nombre_fills',
       'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km',
       'Temperatura_mitjana_ciutat', 'Te_Fills', 'Data_naixement', 'País',
       'Cost_vida_index', 'Transport_public_score', 'Clima_tipus',
       'Increment_base_grup', 'Increment_fills', 'Edat', 'Franja_edat',
       'Increment_edat', 'Cost_band', 'Increment_cost', 'Transport_band',
       'Increment_transport', 'Increment_total_percent',
       'inc_total_percent_capped'],
      dtype='object')

In [255]:
df_merge['País d\'origen'].isna().sum()

np.int64(0)

La lista id_vars define las columnas identificadoras que no deben transformarse en el proceso de melt(). Incluye datos personales (nombre, apellidos, DNI, género), información laboral (grupo profesional, cargo), y atributos contextuales (ciudad, país de origen, edad, franja de edad, hijos, coche, temperatura media).

In [297]:
id_vars = [
    "Nom", "Cognoms", "DNI",
    "Gènere",
    "Ciutat", "País d'origen",
    "Grup Professional", "Càrrec",
    "Te_Fills",
    'Nombre_fills',
    "Te_cotxe",
    "Temperatura_mitjana_ciutat",
    "Edat", "Franja_edat"]

Creo la lista value_vars con todas las columnas que representan medidas cuantitativas (salaris, increments, costos de vida, transport, mobilitat i clima).
Esta lista se utiliza con la función melt() para transformar el dataset a formato largo donde cada variable aparece en una fila con su valor correspondiente.

In [298]:
value_vars = [
    "Salari mensual (€)",
    "Increment_base_grup",
    "Increment_fills",
    "Increment_edat",
    "Increment_cost",
    "Increment_transport",
    "Increment_total_percent",
    "inc_total_percent_capped",
    "Cost_vida_index",
    "Cost_band",
    "Transport_public_score",
    "Transport_band",
    "Km_anuals",
    "Consum_mitja_L_100km",
    "Temperatura_mitjana_ciutat",
    "Clima_tipus"]

In [299]:
df_long = df_merge.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name="variable",
    value_name="valor")

In [300]:
df_long[df_long["DNI"] == df_long.iloc[0]["DNI"]]

,Nom,Cognoms,DNI,Gènere,Ciutat,País d'origen,Grup Professional,Càrrec,Te_Fills,Nombre_fills,Te_cotxe,Temperatura_mitjana_ciutat,Edat,Franja_edat,variable,valor
0,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Salari mensual (€),1469.0
993,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_base_grup,3.5
1986,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_fills,1.5
2979,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_edat,1.5
3972,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_cost,0.0
4965,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_transport,0.5
5958,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Increment_total_percent,7.0
6951,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,inc_total_percent_capped,7.0
7944,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Cost_vida_index,64.0
8937,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Cost_band,low
9930,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Transport_public_score,6.7
10923,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Transport_band,low
11916,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Km_anuals,32108.0
12909,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Consum_mitja_L_100km,25.0
13902,Joana,Gil Navarro,66722344X,Dona,Valladolid,Espanya,Grup B,Cap de projecte,True,3.0,True,10.1,68.0,60+,Clima_tipus,Continental

El dataset se ha transformado a formato largo para facilitar comparaciones, agregaciones y visualizaciones. Cada persona tiene múltiples filas, una por cada variable medida.

## Exercici 3: Creació de variables derivades (Feature Engineering)

Objectiu: generar noves variables derivades a partir de la informació existent i avaluar-ne la qualitat analítica. Tot i que algunes variables de base (com l’edat o el salari) ja han estat introduïdes en exercicis anteriors, en aquest nivell no es valora la seva creació tècnica, sinó la capacitat de transformar-les en indicadors més informatius, la detecció de casos límit o incoherents i la reflexió sobre la utilitat real de les variables generades en un context analític.
Exemples (tria guiada):

>* » Índex de dependència familiar: Salari mensual / (Nombre fills + 1).
>* » Índex de mobilitat: Km anuals / Temperatura mitjana.
>* » Ràtio salari / cost de vida.
>* » Indicador de dependència familiar: Salari / Nombre fills.
>* » Pes de responsabilitat familiar: Nombre fills * Edat.
>* » Indicador de etapa vital: 0 → sense càrregues, 1 → etapa activa, 2 → alta dependència.
Concretament, hauràs de:

### » Crear almenys 3 variables derivades.
>*  Justificar:

>>* La seva utilitat analítica.

>>* Les decisions preses.

**1> Indice Estabilidad laboral:** Relaciona el porcentaje total de incremento salarial con la edad del trabajador. Permite analizar si los aumentos de sueldo están equilibrados respecto a la etapa vital, mostrando perfiles con mayor o menor estabilidad económica.

In [238]:
df_merge['Indice_estabilidad'] = df_merge['Increment_total_percent'] / df_merge['Edat']

**2> Consumo anual estimado de combustible:** Calcula los litros de combustible consumidos al año según kilómetros recorridos y consumo medio. Es útil para evaluar el impacto económico y ambiental de la movilidad privada.

In [239]:
df_merge['Consumo_anual_combustible'] = (df_merge['Km_anuals'] / 100) * df_merge['Consum_mitja_L_100km']

**3> Indicador de movilidad:** Crea una variable booleana que indica si una persona supera un umbral de kilómetros anuales.

In [301]:
df_merge['Movilidad_basica'] = df_merge['Km_anuals'] > 10000

## Exercici 4: Exportació i síntesi de resultats
 Objectiu: consolidar els resultats obtinguts després de la preparació, enriquiment i creació de variables, i generar sortides estructurades reutilitzables per a anàlisi o reporting.
En aquest exercici es vol posar el focus en:

» L'organització de les dades per grups rellevants.
» La generació de datasets finals coherents.
» La capacitat de sintetitzar informació clau.
Aspectes a revisar i analitzar:

» Quin nivell d'agrupació és més adequat per a l'exportació de resultats?
» Com separar dades detallades de dades agregades?
» Quina informació és rellevant per a un ús posterior (anàlisi, visualització, reporting)?
Concretament, hauràs de:

### » Utilitzant un bucle, exportar en 4 fitxers (format .csv o .xlsx) les dades corresponents a cada Grup Professional. Per exemple: dades_GrupA.csv, dades_GrupB.csv...

### » Crear i exportar un cinquè DataFrame (format .csv o .xlsx) que contingui, per a cada Grup Professional:
Nombre total de treballadors.
Salari mitjà.
Edat mediana.

Extraer todos los valores únicos de la columna "Grup Professional" del DataFrame df_merge y los guarda en la variable grups.

In [302]:
grups = df_merge['Grup Professional'].unique()

 Recorremos cada uno de los grupos profesionales presentes en el DataFrame y, para cada grupo, filtramos únicamente las filas que pertenecen a él. Después construimos un nombre de archivo usando ese grupo y finalmente guarda ese subconjunto de datos en un archivo CSV.

In [303]:
for grup in grups:
    df_grup = df_merge[df_merge['Grup Professional'] == grup]
    nom_fitxer = f"dades_{grup}.csv"
    df_grup.to_csv(nom_fitxer, index=False)

Creo un resumen estadístico por cada Grupo Profesional. Primero agrupa el DataFrame df_merge según la columna Grup Professional. Después calcula tres valores para cada grupo: el número total de trabajadores contando la columna **Nom**, el salario medio a partir de **Salari mensual** y la edad mediana usando **Edat**. Finalmente, reset_index() convierte el índice del grupo en una columna normal, dejando el resultado listo como un DataFrame limpio y ordenado.

In [304]:
df_resum = df_merge.groupby('Grup Professional').agg(
    NombreTreballadors=('Nom', 'count'),
    SalariMitja=('Salari mensual (€)', 'mean'),
    EdatMediana=('Edat', 'median')
).reset_index()

Comprobación

In [305]:
df_grup_A = pd.read_csv('dades_Grup A.csv', encoding = 'utf8')

In [306]:
df_grup_A

,Nom,Cognoms,DNI,País d'origen,Ciutat,Gènere,Salari mensual (€),Grup Professional,Càrrec,Nombre_fills,...,Franja_edat,Increment_edat,Cost_band,Increment_cost,Transport_band,Increment_transport,Increment_fills,Increment_total_percent,inc_total_percent_capped,Movilidad_basica
0,Noa,Serra,14308421X,Espanya,Alacant,Dona,1358.0,Grup A,Tècnic IT,4.0,...,60+,1.5,medium,1.0,medium,0.0,1.5,9.0,9.0,False
1,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,Home,1450.0,Grup A,Analista senior,4.0,...,NaN,NaN,low,0.0,low,0.5,1.5,NaN,NaN,False
2,Joana,Torres Díaz,82772208R,Espanya,Valladolid,Dona,982.0,Grup A,Administratiu,0.0,...,60+,1.5,low,0.0,low,0.5,0.0,7.0,7.0,True
3,Emilia,Hoffmann,66851377P,Alemanya,Stuttgart,Dona,1003.0,Grup A,Cap de projecte,NaN,...,60+,1.5,medium,1.0,medium,0.0,NaN,NaN,NaN,False
4,Xavier,Casals,43491314K,Espanya,Alacant,Home,1800.0,Grup A,Analista junior,0.0,...,45-59,2.0,medium,1.0,medium,0.0,0.0,8.0,8.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Marta,Hernández Puig,45997422C,Espanya,A Coruña,Dona,1183.0,Grup A,Analista junior,0.0,...,45-59,2.0,medium,1.0,medium,0.0,0.0,8.0,8.0,True
456,Xavier,García Gil,95100395N,Espanya,Girona,Dona,1437.0,Grup A,Analista senior,NaN,...,60+,1.5,medium,1.0,low,0.5,NaN,NaN,NaN,False
457,Adrià,Hernández Ramos,80771894Q,Espanya,Bilbao,Home,3000.0,Grup A,Analista senior,NaN,...,30-44,1.0,medium,1.0,medium,0.0,NaN,NaN,NaN,True
458,Lucía,Roca Vila,21702378D,Espanya,Alacant,Home,1158.0,Grup A,Data analyst,NaN,...,NaN,NaN,medium,1.0,medium,0.0,NaN,NaN,NaN,False
459,Jordi,Hernández,67755039Y,Espanya,Zaragoza,Dona,1074.0,Grup A,Data analyst,1.0,...,60+,1.5,medium,1.0,medium,0.0,1.5,9.0,9.0,True

# **Nivell 3 – Exploració visual i optimització aplicada**

### Exercici 1: Exploració visual del dataset
Context: Es disposa d'un DataFrame amb un volum elevat de variables. Abans de qualsevol anàlisi específica, és necessari disposar de mecanismes que permetin explorar el dataset de manera ràpida i sistemàtica.

Aquest exercici se centra en crear una funció que ajudi a crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple, un histograma/boxplot si la variable és numèrica, unes barres dels valors més freqüents si és categòrica i unes barres dels anys més freqüents si la dada està en format data.

In [307]:
import os
import matplotlib.pyplot as plt
import seaborn as sns

 Función que genera y guarda automáticamente un gráfico para cada columna del DataFrame. Detecta el tipo de variable y crea el gráfico adecuado.
 >* Crear carpeta de exportación si no existe.
Este bloque comprueba si la carpeta donde guardaremos los gráficos existe. Si no existe, la crea. Así evitamos errores al intentar guardar imágenes.

>* Iteramos columna por columna para generar un gráfico para cada una.  

>* Creamos una figura nueva para cada gráfico y evitamos que se solapen.

>* Detectar tipo de variable. Según el tipo de dato, decidimos qué gráfico crear.

>* Gráficos para variables numéricas. Para variables numéricas generamos un histograma y un boxplot.

>* Gráficos para variables categóricas. Para variables categóricas mostramos las frecuencias de los valores más comunes.

>* Gráficos para variables de fecha. Para fechas mostramos la distribución por año.

>* Gráficos para variables booleanas. Para booleanos mostramos cuántos True y False hay.

>* BLOQUE 9: Caso no reconocido. Si aparece un carácter raro, simplemente lo ignoramos.

>* Guardar gráfico. Guardamos el gráfico con el nombre de la columna en la carpeta indicada.

In [308]:
def explorar_dataframe(df, carpeta="plots"):
    if not os.path.exists(carpeta):
        os.makedirs(carpeta)

    for col in df.columns:
        serie = df[col]

        plt.figure(figsize=(8, 5))

        if serie.dtype == "float64" or serie.dtype == "int64":

            plt.subplot(1, 2, 1)
            sns.histplot(serie.dropna(), kde=True)
            plt.title(f"Histograma de {col}")

            plt.subplot(1, 2, 2)
            sns.boxplot(x=serie.dropna())
            plt.title(f"Boxplot de {col}")

        elif serie.dtype == "object":

            conteo = serie.value_counts().head(10)
            sns.barplot(x=conteo.values, y=conteo.index)
            plt.title(f"Valores más frecuentes de {col}")

        elif str(serie.dtype).startswith("datetime"):

            años = serie.dt.year.value_counts().sort_index()
            sns.barplot(x=años.index, y=años.values)
            plt.title(f"Distribución por año de {col}")
            plt.xticks(rotation=45)

        elif serie.dtype == "bool":

            conteo = serie.value_counts()
            sns.barplot(x=conteo.index.astype(str), y=conteo.values)
            plt.title(f"Distribución de valores booleanos en {col}")

        else:

            plt.text(0.5, 0.5, f"No se puede graficar la columna {col}", ha="center")

        ruta = os.path.join(carpeta, f"{col}.png")
        plt.tight_layout()
        plt.savefig(ruta)
        plt.close()

        print(f"Gráficos generados y guardados en la carpeta: {carpeta}")

In [309]:
import seaborn as sns

df_iris = sns.load_dataset("iris")
explorar_dataframe(df_iris, carpeta="plots_iris")

Gráficos generados y guardados en la carpeta: plots_iris
Gráficos generados y guardados en la carpeta: plots_iris
Gráficos generados y guardados en la carpeta: plots_iris
Gráficos generados y guardados en la carpeta: plots_iris
Gráficos generados y guardados en la carpeta: plots_iris

In [310]:
explorar_dataframe(df_merge, carpeta="plots_df_merge")

Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge
Gráficos generados y guardados en la carpeta: plots_df_merge

### Exercici 2: Optimització de rutes (problema aplicat)
Context: L'empresa no disposa d'un control fiable del quilometratge dels desplaçaments dels seus treballadors. Abans d'implementar un sistema avançat, es vol fer una prova pilot amb treballadors ubicats a Espanya.
Per a aquesta prova:

» Es treballa amb una matriu de distàncies entre ciutats.
»Es vol una solució simple, raonable i explicable.
» No es busca la ruta òptima, sinó una aproximació coherent.
Carrega l'arxiu matriu_distancies.xlsx a pandas de manera que les files i columnes siguin les ciutats i s'eliminin "Las Palmas de Gran Canaria" i "Palma".

Desenvolupa una funció que:

» Rebi: una ciutat d'origen i una ciutat de destinació.
» Retorni: l'ordre de les ciutats visitades (ruta) i la distància total recorreguda.
La ruta s'ha de construir seguint una estratègia senzilla: anar sempre a la ciutat no visitada més propera fins a arribar a la destinació.

In [311]:
df_dist = pd.read_excel("matriu_distancies.xlsx", index_col=0)

In [312]:
ciutats_a_eliminar = ["Palma", "Las Palmas de Gran Canaria"]

In [313]:
df_dist = df_dist.drop(index=ciutats_a_eliminar, columns=ciutats_a_eliminar)


    Función que calcula una ruta aproximada entre dos ciudades
    usando una estrategia greedy: siempre ir a la ciudad no visitada
    más cercana hasta llegar a la ciudad destino.

  BLOQUE 1: Inicialización ---
  Creamos una lista para guardar el orden de ciudades visitadas.

  Conjunto para marcar ciudades ya visitadas.

Ciudad actual desde la que buscamos la siguiente.

 Distancia total acumulada.

  BLOQUE 2: Bucle principal ---
  Continuamos hasta llegar a la ciudad destino.

Distancias desde la ciudad actual a todas las demás.

Filtramos ciudades no visitadas.

Elegimos la ciudad más cercana.

Actualizamos ruta y distancia.

Marcamos como visitada.

Avanzamos a la siguiente ciudad.

  BLOQUE 3: Resultado ---
Devolvemos la ruta completa y la distancia total recorrida.

In [314]:
def ruta_greedy(origen, destinacio, df_dist):

    ruta = [origen]

    visitadas = set([origen])

    actual = origen

    distancia_total = 0

    while actual != destinacio:

        distancias = df_dist.loc[actual]

        no_visitadas = distancias.drop(labels=list(visitadas))

        siguiente_ciudad = no_visitadas.idxmin()
        distancia_siguiente = no_visitadas.min()

        ruta.append(siguiente_ciudad)
        distancia_total += distancia_siguiente

        visitadas.add(siguiente_ciudad)

        actual = siguiente_ciudad

    return ruta, distancia_total

In [315]:
ruta, dist_total = ruta_greedy("Barcelona", "Sevilla", df_dist)
print("Ruta:", ruta)
print("Distancia total:", dist_total, "km")

Ruta: ['Barcelona', 'Hospitalet de Llobregat', 'Zaragoza', 'Valencia', 'Alicante', 'Murcia', 'Córdoba', 'Sevilla']
Distancia total: 1138.0 km